const User = require('../models/User');
const FitnessLog = require('../models/FitnessLog');

const ROLE_ID_PREFIX = {
  student: 'STU',
  mentor: 'MEN',
  admin: 'ADM',
};

const getRoleIdField = (role) => {
  if (role === 'mentor') return 'mentorId';
  if (role === 'admin') return 'adminId';
  return 'studentId';
};

const getAccountId = (user) => {
  return user.studentId || user.mentorId || user.adminId || null;
};

const generateRoleId = async (role) => {
  const prefix = ROLE_ID_PREFIX[role] || ROLE_ID_PREFIX.student;
  const currentYear = new Date().getFullYear();
  let isUnique = false;
  let newId = '';

  while (!isUnique) {
    const randomDigits = Math.floor(1000 + Math.random() * 9000);
    newId = `${prefix}${currentYear}${randomDigits}`;

    const existing = await User.findOne({
      $or: [
        { studentId: newId },
        { mentorId: newId },
        { adminId: newId },
      ],
    });

    if (!existing) isUnique = true;
  }

  return newId;
};

const sanitizeAcademicFields = (data, role) => {
  if (role !== 'student') {
    delete data.university;
    delete data.department;
    delete data.graduateType;
    delete data.year;
    delete data.dateOfBirth;
    delete data.age;
    delete data.gender;
  }
  return data;
};

const formatUser = (user) => ({
  _id: user._id,
  firstName: user.firstName,
  lastName: user.lastName,
  email: user.email,
  role: user.role,
  university: user.university || '',
  department: user.department || '',
  graduateType: user.graduateType || '',
  year: user.year || '',
  dateOfBirth: user.dateOfBirth || null,
  age: user.age || null,
  gender: user.gender || '',
  isActive: user.isActive,
  points: user.points || 0,
  level: user.role === 'student' ? Math.floor((user.points || 0) / 500) + 1 : null,
  accountId: getAccountId(user),
  createdAt: user.createdAt,
  updatedAt: user.updatedAt,
});

// @desc    Get all users and their role details
exports.getUsers = async (req, res) => {
  try {
    const users = await User.find()
      .select('firstName lastName email role university department graduateType year dateOfBirth age gender isActive points currentStreak studentId mentorId adminId createdAt updatedAt')
      .sort({ role: 1, lastName: 1, firstName: 1 });

    res.status(200).json({
      success: true,
      data: users.map(formatUser),
    });
  } catch (error) {
    console.error('Get Users Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while fetching users',
      error: error.message,
    });
  }
};

// @desc    Create a new user from admin panel
exports.createUser = async (req, res) => {
  try {
    const {
      firstName,
      lastName,
      email,
      password,
      role,
      university,
      department,
      graduateType,
      year,
      dateOfBirth,
      age,
      gender,
    } = req.body;

    if (!firstName || !lastName || !email || !password) {
      return res.status(400).json({
        success: false,
        message: 'First name, last name, email, and password are required',
      });
    }

    const existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({
        success: false,
        message: 'A user with that email already exists',
      });
    }

    const targetRole = role || 'student';
    const autoGeneratedId = await generateRoleId(targetRole);
    const idField = getRoleIdField(targetRole);

    const userData = sanitizeAcademicFields({
      firstName,
      lastName,
      email,
      password,
      role: targetRole,
      university,
      department,
      graduateType,
      year,
      dateOfBirth,
      age,
      gender,
      [idField]: autoGeneratedId,
    }, targetRole);

    const user = await User.create(userData);

    res.status(201).json({
      success: true,
      data: formatUser(user),
    });
  } catch (error) {
    console.error('Create User Error:', error);
    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map((err) => err.message);
      return res.status(400).json({
        success: false,
        message: messages.join(', '),
      });
    }
    res.status(500).json({
      success: false,
      message: 'Server error while creating user',
      error: error.message,
    });
  }
};

// @desc    Update user details from admin panel
exports.updateUser = async (req, res) => {
  try {
    const { userId } = req.params;
    const {
      firstName,
      lastName,
      email,
      role,
      university,
      department,
      graduateType,
      year,
      dateOfBirth,
      age,
      gender,
      isActive,
    } = req.body;

    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({
        success: false,
        message: 'User not found',
      });
    }

    if (email && email !== user.email) {
      const emailTaken = await User.findOne({ email });
      if (emailTaken) {
        return res.status(400).json({
          success: false,
          message: 'Another account is already using that email',
        });
      }
    }

    const newRole = role || user.role;
    const roleChanged = newRole !== user.role;

    user.firstName = firstName ?? user.firstName;
    user.lastName = lastName ?? user.lastName;
    user.email = email ?? user.email;
    user.role = newRole;
    user.isActive = typeof isActive === 'boolean' ? isActive : user.isActive;

    if (roleChanged) {
      user.studentId = undefined;
      user.mentorId = undefined;
      user.adminId = undefined;
      const newIdField = getRoleIdField(newRole);
      user[newIdField] = await generateRoleId(newRole);
    }

    const updatedData = sanitizeAcademicFields({
      university,
      department,
      graduateType,
      year,
      dateOfBirth,
      age,
      gender,
    }, newRole);

    Object.entries(updatedData).forEach(([key, value]) => {
      if (typeof value !== 'undefined') {
        user[key] = value;
      }
    });

    await user.save();

    res.status(200).json({
      success: true,
      data: formatUser(user),
    });
  } catch (error) {
    console.error('Update User Error:', error);
    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map((err) => err.message);
      return res.status(400).json({
        success: false,
        message: messages.join(', '),
      });
    }
    res.status(500).json({
      success: false,
      message: 'Server error while updating user',
      error: error.message,
    });
  }
};

// @desc    Delete a user from admin panel
exports.deleteUser = async (req, res) => {
  try {
    const { userId } = req.params;

    if (req.user.id === userId) {
      return res.status(400).json({
        success: false,
        message: 'Admins cannot delete their own account',
      });
    }

    const user = await User.findById(userId);
    if (!user) {
      return res.status(404).json({
        success: false,
        message: 'User not found',
      });
    }

    if (user.role === 'mentor' && user.assignedStudents?.length) {
      await User.updateMany(
        { _id: { $in: user.assignedStudents } },
        { $set: { assignedMentor: null } }
      );
    }

    if (user.role === 'student' && user.assignedMentor) {
      await User.findByIdAndUpdate(user.assignedMentor, {
        $pull: { assignedStudents: user._id },
      });
    }

    await User.findByIdAndDelete(userId);

    res.status(200).json({
      success: true,
      message: 'User deleted successfully',
    });
  } catch (error) {
    console.error('Delete User Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while deleting user',
      error: error.message,
    });
  }
};

// @desc    Get all mentors for admin
exports.getMentors = async (req, res) => {
  try {
    const mentors = await User.find({ role: 'mentor' })
      .select('firstName lastName email mentorId university department assignedStudents createdAt updatedAt')
      .populate({
        path: 'assignedStudents',
        select: 'firstName lastName email studentId',
      });

    res.status(200).json({
      success: true,
      count: mentors.length,
      data: mentors.map((mentor) => ({
        _id: mentor._id,
        firstName: mentor.firstName,
        lastName: mentor.lastName,
        email: mentor.email,
        mentorId: mentor.mentorId,
        university: mentor.university || '',
        department: mentor.department || '',
        assignedStudentsCount: mentor.assignedStudents?.length || 0,
        assignedStudents: mentor.assignedStudents || [],
        createdAt: mentor.createdAt,
        updatedAt: mentor.updatedAt,
      })),
    });
  } catch (error) {
    console.error('Get Mentors Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while fetching mentors',
      error: error.message,
    });
  }
};

// @desc    Assign students to a mentor
exports.assignStudents = async (req, res) => {
  try {
    const { mentorId } = req.params;
    const { studentIds } = req.body;

    if (!Array.isArray(studentIds) || studentIds.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'studentIds array is required',
      });
    }

    const uniqueStudentIds = [...new Set(studentIds)];

    const mentor = await User.findById(mentorId);
    if (!mentor || mentor.role !== 'mentor') {
      return res.status(404).json({
        success: false,
        message: 'Mentor not found',
      });
    }

    const students = await User.find({ _id: { $in: uniqueStudentIds }, role: 'student' });
    if (students.length !== uniqueStudentIds.length) {
      return res.status(404).json({
        success: false,
        message: 'One or more student IDs are invalid or not students',
      });
    }

    const updatedStudentIds = new Set(
      mentor.assignedStudents.map((id) => id.toString())
    );

    const previousMentorIds = [
      ...new Set(
        students
          .map((student) => student.assignedMentor?.toString())
          .filter((id) => id && id !== mentor._id.toString())
      ),
    ];

    if (previousMentorIds.length > 0) {
      await User.updateMany(
        { _id: { $in: previousMentorIds } },
        { $pull: { assignedStudents: { $in: students.map((student) => student._id) } } }
      );
    }

    await Promise.all(
      students.map(async (student) => {
        student.assignedMentor = mentor._id;
        await student.save();
        updatedStudentIds.add(student._id.toString());
      })
    );

    mentor.assignedStudents = Array.from(updatedStudentIds);
    await mentor.save();

    res.status(200).json({
      success: true,
      message: 'Students assigned successfully',
      data: {
        mentorId: mentor._id,
        assignedStudents: mentor.assignedStudents,
      },
    });
  } catch (error) {
    console.error('Assign Students Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while assigning students',
      error: error.message,
    });
  }
};

// @desc    Unassign a student from a mentor
exports.unassignStudent = async (req, res) => {
  try {
    const { mentorId, studentId } = req.params;

    const mentor = await User.findById(mentorId);
    if (!mentor || mentor.role !== 'mentor') {
      return res.status(404).json({
        success: false,
        message: 'Mentor not found',
      });
    }

    const student = await User.findById(studentId);
    if (!student || student.role !== 'student') {
      return res.status(404).json({
        success: false,
        message: 'Student not found',
      });
    }

    mentor.assignedStudents = (mentor.assignedStudents || []).filter(
      (id) => id.toString() !== student._id.toString()
    );

    if (student.assignedMentor?.toString() === mentor._id.toString()) {
      student.assignedMentor = null;
      await student.save();
    }

    await mentor.save();

    res.status(200).json({
      success: true,
      message: 'Student unassigned successfully',
      data: {
        mentorId: mentor._id,
        studentId: student._id,
      },
    });
  } catch (error) {
    console.error('Unassign Student Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while unassigning student',
      error: error.message,
    });
  }
};

// @desc    Get aggregate university-wide wellness statistics
// @route   GET /api/admin/aggregate-stats
// @access  Private (Admin/Mentor only)
exports.getAggregateStats = async (req, res) => {
  try {
    // Only allow admin and mentor to access this route
    if (req.user.role !== 'admin' && req.user.role !== 'mentor') {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to access aggregated stats',
      });
    }

    // 1. Get Population Stats (System Engagement)
    const totalUsers = await User.countDocuments({ role: 'student' });
    const DAU = await User.countDocuments({ 
        role: 'student', 
        lastLogDate: { $gte: new Date(new Date().setHours(0,0,0,0)) } 
    });

    const activeUsers = await User.find({ role: 'student', currentStreak: { $gt: 0 } });
    const avgStreak = activeUsers.length > 0 
        ? Math.round(activeUsers.reduce((sum, u) => sum + (u.currentStreak || 0), 0) / activeUsers.length)
        : 0;

    // 1b. Mentor Assignment Summary
    const totalMentors = await User.countDocuments({ role: 'mentor' });
    const unassignedStudents = await User.countDocuments({ role: 'student', assignedMentor: null });
    const mentors = await User.find({ role: 'mentor' })
      .select('firstName lastName mentorId assignedStudents')
      .lean();
    const mentorLoad = mentors.map((m) => ({
      name: `${m.firstName} ${m.lastName}`,
      mentorId: m.mentorId || null,
      studentCount: (m.assignedStudents || []).length,
    }));

    // 2. Department-level Activity & Stress Averages over the last 30 days
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const departmentStats = await FitnessLog.aggregate([
      {
        $match: { date: { $gte: thirtyDaysAgo } }
      },
      {
        // Join with the User collection to get department and role
        $lookup: {
          from: 'users',
          localField: 'user',
          foreignField: '_id',
          as: 'userDetails'
        }
      },
      {
        $unwind: '$userDetails'
      },
      {
        $match: { 'userDetails.role': 'student' } // Only count students
      },
      {
        // Group by department
        $group: {
          _id: '$userDetails.department',
          avgStressLevel: { $avg: '$stressLevel' },
          avgSleepHours: { $avg: '$sleep.hours' },
          avgActiveMinutes: { $avg: '$activeMinutes' },
          logCount: { $sum: 1 }
        }
      },
      {
        $project: {
            department: { $ifNull: ['$_id', 'Unknown'] },
            avgStressLevel: { $round: ['$avgStressLevel', 1] },
            avgSleepHours: { $round: ['$avgSleepHours', 1] },
            avgActiveMinutes: { $round: ['$avgActiveMinutes', 0] },
            logCount: 1,
            _id: 0
        }
      },
      { $sort: { logCount: -1 } }
    ]);

    // 3. Overall Campus Stress Timeseries (last 14 days)
    const fourteenDaysAgo = new Date();
    fourteenDaysAgo.setDate(fourteenDaysAgo.getDate() - 14);

    const stressTimeseries = await FitnessLog.aggregate([
      {
         $match: { date: { $gte: fourteenDaysAgo }, stressLevel: { $exists: true } }
      },
      {
         $group: {
            _id: { $dateToString: { format: "%Y-%m-%d", date: "$date" } },
            avgStress: { $avg: '$stressLevel' },
            avgSleep: { $avg: '$sleep.hours' }
         }
      },
      {
         $project: {
            date: '$_id',
            avgStress: { $round: ['$avgStress', 1] },
            avgSleep: { $round: ['$avgSleep', 1] },
            _id: 0
         }
      },
      { $sort: { date: 1 } }
    ]);

    res.status(200).json({
      success: true,
      data: {
        engagement: {
            totalStudents: totalUsers,
            dailyActiveUsers: DAU,
            engagementRate: totalUsers > 0 ? Math.round((DAU / totalUsers) * 100) : 0,
            averageCurrentStreak: avgStreak
        },
        mentorSummary: {
            totalMentors,
            unassignedStudents,
            mentorLoad,
        },
        departmentStats,
        stressTimeseries
      },
    });
  } catch (error) {
    console.error('Aggregate Stats Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while aggregating stats',
      error: error.message,
    });
  }
};
