const User = require('../models/User');
const jwt = require('jsonwebtoken');

const ALLOWED_HEALTH_CONSIDERATIONS = [
  'breathing_issues',
  'heart_restriction',
  'joint_pain',
  'diabetes_concern',
  'doctor_exercise_limit',
  'dietary_restriction',
  'vegetarian',
  'vegan',
];

// ==================== HELPER FUNCTIONS ====================

// Generate JWT Token
const generateToken = (userId) => {
  return jwt.sign({ id: userId }, process.env.JWT_SECRET, {
    expiresIn: '30d', // Token expires in 30 days
  });
};

const formatUserWithMessages = (userDoc) => {
  const user = userDoc.toObject ? userDoc.toObject() : userDoc;
  delete user.password;

  user.encouragementMessages = (user.encouragementMessages || []).map((msg) => ({
    ...msg,
    fromName: msg.from
      ? `${msg.from.firstName || ''} ${msg.from.lastName || ''}`.trim()
      : 'Mentor',
  }));

  return user;
};

// Send response with token
const sendTokenResponse = (user, statusCode, res) => {
  const token = generateToken(user._id);

  res.status(statusCode).json({
    success: true,
    token,
    user: user.getPublicProfile(),
  });
};

// ==================== AUTH CONTROLLERS ====================

// @desc    Register a new user
// @route   POST /api/auth/register
// @access  Public
exports.register = async (req, res) => {
  try {
    const {
      firstName,
      lastName,
      email,
      password,
      university,
      department,
      graduateType,
      year,
      dateOfBirth,
      age,
      gender,
      role,
    } = req.body;

    // Check if user already exists
    const existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({
        success: false,
        message: 'User with this email already exists',
      });
    }

    const targetRole = role || 'student';

    // Auto-generate ID based on role e.g., STU20241834, MEN20248812
    const generateId = async () => {
      let isUnique = false;
      let newId = '';
      const prefix = targetRole === 'mentor' ? 'MEN' : targetRole === 'admin' ? 'ADM' : 'STU';
      const currentYear = new Date().getFullYear();

      while (!isUnique) {
        const randomDigits = Math.floor(1000 + Math.random() * 9000); // 4 digit random
        newId = `${prefix}${currentYear}${randomDigits}`;
        const existing = await User.findOne({
          $or: [
            { studentId: newId },
            { mentorId: newId },
            { adminId: newId },
          ],
        });
        if (!existing) isUnique = true;
      }
      return newId;
    };

    const autoGeneratedId = await generateId();
    const idField =
      targetRole === 'mentor'
        ? 'mentorId'
        : targetRole === 'admin'
          ? 'adminId'
          : 'studentId';

    // Create new user
    const user = await User.create({
      firstName,
      lastName,
      email,
      password,
      [idField]: autoGeneratedId,
      university,
      department,
      graduateType,
      year,
      dateOfBirth,
      age,
      gender,
      role: role || 'student',
    });

    // Send token response
    sendTokenResponse(user, 201, res);
  } catch (error) {
    console.error('Register Error:', error);

    // Handle validation errors
    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map((err) => err.message);
      return res.status(400).json({
        success: false,
        message: messages.join(', '),
      });
    }

    res.status(500).json({
      success: false,
      message: 'Server error during registration',
      error: error.message,
    });
  }
};

// @desc    Login user
// @route   POST /api/auth/login
// @access  Public
exports.login = async (req, res) => {
  try {
    const { email, password } = req.body;

    // Validate email and password
    if (!email || !password) {
      return res.status(400).json({
        success: false,
        message: 'Please provide email and password',
      });
    }

    // Find user by email (include password field)
    const user = await User.findOne({ email }).select('+password');

    if (!user) {
      return res.status(401).json({
        success: false,
        message: 'Invalid credentials',
      });
    }

    // Check if password matches
    const isPasswordMatch = await user.comparePassword(password);

    if (!isPasswordMatch) {
      return res.status(401).json({
        success: false,
        message: 'Invalid credentials',
      });
    }

    // Update last login
    user.lastLogin = Date.now();
    await user.save();

    // Send token response
    sendTokenResponse(user, 200, res);
  } catch (error) {
    console.error('Login Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error during login',
      error: error.message,
    });
  }
};

// @desc    Get current logged-in user
// @route   GET /api/auth/me
// @access  Private
exports.getMe = async (req, res) => {
  try {
    // req.user is set by the auth middleware
    const user = await User.findById(req.user.id).populate({
      path: 'encouragementMessages.from',
      select: 'firstName lastName role',
    });

    res.status(200).json({
      success: true,
      user: formatUserWithMessages(user),
    });
  } catch (error) {
    console.error('Get Me Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message,
    });
  }
};

// @desc    Mark all encouragement messages as read
// @route   PUT /api/auth/messages/read
// @access  Private
exports.markMessagesRead = async (req, res) => {
  try {
    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(404).json({
        success: false,
        message: 'User not found',
      });
    }

    user.encouragementMessages = (user.encouragementMessages || []).map((msg) => ({
      ...msg.toObject(),
      read: true,
    }));

    await user.save();

    res.status(200).json({
      success: true,
      message: 'Messages marked as read',
    });
  } catch (error) {
    console.error('Mark Messages Read Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error while updating messages',
      error: error.message,
    });
  }
};

// @desc    Update user profile
// @route   PUT /api/auth/updateprofile
// @access  Private
exports.updateProfile = async (req, res) => {
  try {
    const fieldsToUpdate = {
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      department: req.body.department,
      graduateType: req.body.graduateType,
      year: req.body.year,
      dateOfBirth: req.body.dateOfBirth,
      age: req.body.age,
      gender: req.body.gender,
      height: req.body.height,
      weight: req.body.weight,
      fitnessGoals: req.body.fitnessGoals,
      targetWeight: req.body.targetWeight,
      targetSteps: req.body.targetSteps,
      targetCalories: req.body.targetCalories,
      targetSleep: req.body.targetSleep,
    };

    if (req.body.healthConsiderations !== undefined) {
      if (!Array.isArray(req.body.healthConsiderations)) {
        return res.status(400).json({
          success: false,
          message: 'healthConsiderations must be an array of valid values',
        });
      }

      const invalidValues = req.body.healthConsiderations.filter(
        (value) => !ALLOWED_HEALTH_CONSIDERATIONS.includes(value)
      );

      if (invalidValues.length > 0) {
        return res.status(400).json({
          success: false,
          message: `Invalid healthConsiderations values: ${invalidValues.join(', ')}`,
        });
      }

      fieldsToUpdate.healthConsiderations = [...new Set(req.body.healthConsiderations)];
    }

    // Remove undefined fields
    Object.keys(fieldsToUpdate).forEach(
      (key) => fieldsToUpdate[key] === undefined && delete fieldsToUpdate[key]
    );

    const user = await User.findByIdAndUpdate(req.user.id, fieldsToUpdate, {
      new: true, // Return updated document
      runValidators: true, // Run validation on update
    });

    res.status(200).json({
      success: true,
      user: user.getPublicProfile(),
    });
  } catch (error) {
    console.error('Update Profile Error:', error);

    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map((err) => err.message);
      return res.status(400).json({
        success: false,
        message: messages.join(', '),
      });
    }

    res.status(500).json({
      success: false,
      message: 'Server error during profile update',
      error: error.message,
    });
  }
};

// @desc    Update password
// @route   PUT /api/auth/updatepassword
// @access  Private
exports.updatePassword = async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;

    if (!currentPassword || !newPassword) {
      return res.status(400).json({
        success: false,
        message: 'Please provide current and new password',
      });
    }

    const user = await User.findById(req.user.id).select('+password');

    // Check current password
    const isMatch = await user.comparePassword(currentPassword);
    if (!isMatch) {
      return res.status(401).json({
        success: false,
        message: 'Current password is incorrect',
      });
    }

    // Update password
    user.password = newPassword;
    await user.save();

    sendTokenResponse(user, 200, res);
  } catch (error) {
    console.error('Update Password Error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error during password update',
      error: error.message,
    });
  }
};
const googleFitService = require('../services/googleFitService');

// @desc    Link Google Fit account using auth code
// @route   POST /api/auth/googlefit/link
// @access  Private
exports.linkGoogleFit = async (req, res) => {
  try {
    const { code } = req.body;

    if (!code) {
      return res.status(400).json({
        success: false,
        message: 'No authorization code provided',
      });
    }

    // Exchange code for tokens
    const tokens = await googleFitService.getTokensFromCode(code);

    // Save tokens to user
    const user = await User.findById(req.user.id);
    if (!user) {
      return res.status(404).json({
        success: false,
        message: 'User not found',
      });
    }

    user.googleRefreshToken = tokens.refresh_token || user.googleRefreshToken;
    user.googleAccessToken = tokens.access_token;
    user.isGoogleFitConnected = true;
    user.googleFitSyncEnabled = true;

    await user.save();

    res.status(200).json({
      success: true,
      message: 'Google Fit linked successfully',
      isGoogleFitConnected: true,
      access_token: tokens.access_token,
      expiry_date: tokens.expiry_date,
    });
  } catch (error) {
    console.error('Google Fit Link Error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to link Google Fit',
      error: error.message,
    });
  }
};
